### PR TITLE
Create courses page

### PR DESCRIPTION
**Pull request by kmcgillivray**

### CODE REVIEW

**Comment by kmcgillivray** [comment]
@ccschmitz @timgremore Check out the [codeconvoy.com/courses](http://codeconvoy.com/courses) page, it's very rough, but something we can direct people to if they're interested. Thoughts?

**Comment by kmcgillivray** [comment]
@ccschmitz We can replace that form with MailChimp or whatever works for the list you have set up already.

**Comment by timgremore** [comment]
I think it's a strong start and we should weave it into the workshop. Just need some place for attendees to respond - nice work!

**Comment by ccschmitz** [comment]
You are the man, @kmcgillivray! I just added you to our MailChimp account. Let me know if you want to wrap this up or if you'd like me to take care of it during the event tomorrow.

**Pull request merged**
